<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="coverlet.MTP" Version="8.0.1" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Unreal.Encryption\Unreal.Encryption.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CompressedChunk\compressed-chunk-0.dump">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="CompressedChunk\compressed-chunk-1.dump">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="CompressedChunk\compressed.dump">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>